### ISSUE TITLE
When packing, got told to `vagrant up` but the machine is already running

### ISSUE THREAD

**Issue by vionemc** [paulproteus/ampache-sandstorm-prototype#17]
I tried to pack using Sandstorm, but then it shows me this error instead.

```
D:\xampp\htdocs\PHP projects\Asheesh Laroia\ampache-sandstorm-prototype>vagrant-spk pack ~/projects/package.spk
~/projects/package.spk
Calling 'vagrant' 'ssh' '-c' 'cd /opt/app/.sandstorm/ && spk pack --keyring=/host-dot-sandstorm/sandstorm-keyring --pkg-def=/opt/app/.sandstorm/sandstorm-pkgdef.capnp:pkgdef /home/vagrant/sandstorm-package.spk && spk verify --details /home/vagrant/sandstorm-package.spk && mv /home/vagrant/sandstorm-package.spk /opt/app/sandstorm-package.spk' in D:\xampp\htdocs\PHP projects\Asheesh Laroia\ampache-sandstorm-prototype\.sandstorm
VM must be running to open SSH connection. Run `vagrant up`
to start the virtual machine.
Traceback (most recent call last):
  File "<string>", line 1022, in <module>
  File "<string>", line 1019, in main
  File "<string>", line 819, in pack
  File "<string>", line 288, in call_vagrant_command
  File "subprocess.py", line 540, in check_call
subprocess.CalledProcessError: Command '['vagrant', 'ssh', '-c', 'cd /opt/app/.sandstorm/ && spk pack --keyring=/host-dot-sandstorm/sandstorm-keyring --pkg-def=/opt/app/.sandstorm/sandstorm-pkgdef.capnp:pkgdef /home/vagrant/sandstorm-package.spk && spk verify --details /home/vagrant/sandstorm-package.spk && mv /home/vagrant/sandstorm-package.spk /opt/app/sandstorm-package.spk']' returned non-zero exit status 1
vagrant-spk returned -1
```

But the problem is, the machine is already running. Prove:

```
D:\xampp\htdocs\PHP projects\Asheesh Laroia\ampache-sandstorm-prototype>vagrant global-status
id       name    provider   state    directory                                                                          
------------------------------------------------------------------------------------------------------------------------
0191611  default virtualbox running  D:/xampp/htdocs/PHP projects/Asheesh Laroia/ampache-sandstorm-prototype   
```

**Comment by vionemc** [comment]
Just in case it's caused by port colliding, I tried `vagrant-spk vm halt` but it didn't halt the already running VM

**Comment by vionemc** [comment]
I succeed powering off the running VM using `vagrant-spk vm halt {VM id}`, but I still can't run a new VM because of port colliding.

**Comment by vionemc** [comment]
Every VM is turned off, XAMPP is turned off, and http://local.sandstorm.io:6080/apps is still accessible. Is that possible?

**Comment by vionemc** [comment]
The error goes away! I solved it by forcing the VBox Headless process to stop through Windows Task Manager.

I hope it helps somebody out there.

**Comment by paulproteus** [comment]
I don't know exactly what was happening for you, but I can say that when I experience similar things, I tend to use the VirtualBox GUI to understand it.

**Comment by vionemc** [comment]
Yup, but the GUI didn't show anything wrong. That's the hard part.

**Comment by paulproteus** [comment]
Gotcha. That's weird; I wonder if it's because you created the VM with a previous version of VirtualBox so the new version couldn't keep track of it.

**Comment by vionemc** [comment]
Nah.. I restarted, so that's not a problem.

**Comment by paulproteus** [comment]
Good to know. I'm without any further ideas, then!​
