### ISSUE TITLE
Got error when packing using Sandstorm in Windows 10

### ISSUE THREAD

**Issue by vionemc** [paulproteus/ampache-sandstorm-prototype#18]
When I try to pack using Sandstorm, I got this error:

```
D:\xampp\htdocs\PHP projects\Asheesh Laroia\ampache-sandstorm-prototype>vagrant-spk pack ~/projects/package.spk
~/projects/package.spk
Calling 'vagrant' 'ssh' '-c' 'cd /opt/app/.sandstorm/ && spk pack --keyring=/host-dot-sandstorm/sandstorm-keyring --pkg-def=/opt/app/.sandstorm/sandstorm-pkgdef.capnp:pkgdef /home/vagrant/sandstorm-package.spk && spk verify --details /home/vagrant/sandstorm-package.spk && mv /home/vagrant/sandstorm-package.spk /opt/app/sandstorm-package.spk' in D:\xampp\htdocs\PHP projects\Asheesh Laroia\ampache-sandstorm-prototype\.sandstorm
qdfxn82a2r6sjgxd075p3d3gzyyekndnajs3uq9ynfjwkf5uu30h
{ "appId": "qdfxn82a2r6sjgxd075p3d3gzyyekndnajs3uq9ynfjwkf5uu30h",
  "packageId": "70543ff8c9383a3b9114d1f9e0599827",
  "title": {"defaultText": "Sandstorm Showcase"},
  "version": 0,
  "marketingVersion": {"defaultText": "0.0.0"},
  "metadata": {
    "icons": {},
    "website": "http:\/\/example.com",
    "codeUrl": "http:\/\/example.com",
    "license": {"none": null},
    "categories": [],
    "author": {"contactEmail": "youremail@example.com", "upstreamAuthor": "Example App Team"},
    "shortDescription": {"defaultText": "one-to-three words"},
    "screenshots": [] } }
Connection to 127.0.0.1 closed.
Traceback (most recent call last):
  File "<string>", line 1022, in <module>
  File "<string>", line 1019, in main
  File "<string>", line 821, in pack
WindowsError: [Error 3] The system cannot find the path specified
vagrant-spk returned -1
```

**Comment by paulproteus** [comment]
Try using:

`vagrant-spk pack ../package.spk`

I think a problem is that `~` means something on Mac OS & Linux but doesn't on Windows.

**Comment by vionemc** [comment]
That's it! Silly me. I just copy pasted the command from the tutorial without evaluating it. Thanks!

Note: In Windows, we should use an absolute path.

**Comment by paulproteus** [comment]
Or it's a silly tutorial that doesn't lend itself to copy-pasting!
