### ISSUE TITLE
Can't read file even though it really exists

### ISSUE THREAD

**Issue by vionemc** [paulproteus/ampache-sandstorm-prototype#20]
When I run `vagrant-spk dev` with image file set in `sandstorm-pkgdef.capnp` I got this error:

```
D:\xampp\htdocs\PHP projects\Asheesh Laroia\ampache-sandstorm-prototype>vagrant-spk dev
Calling 'vagrant' 'ssh' '-c' '/opt/app/.sandstorm/build.sh && cd /opt/app/.sandstorm && spk dev --pkg-def=/opt/app/.sandstorm/sandstorm-pkgdef.capnp:pkgdef' in D:\xampp\htdocs\PHP projects\Asheesh Laroia\ampache-sandstorm-prototype\.sandstorm
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Generating autoload files
> ComponentInstaller\Installer::postAutoloadDump
Compiling component files
*** Uncaught exception ***
/opt/app/.sandstorm/sandstorm-pkgdef.capnp:130: failed: Couldn't read file for embed: /opt/app/images/preview/catalog.jpg
Connection to 127.0.0.1 closed.
Traceback (most recent call last):
  File "<string>", line 1022, in <module>
  File "<string>", line 1019, in main
  File "<string>", line 674, in dev
  File "<string>", line 288, in call_vagrant_command
  File "subprocess.py", line 540, in check_call
subprocess.CalledProcessError: Command '['vagrant', 'ssh', '-c', '/opt/app/.sandstorm/build.sh && cd /opt/app/.sandstorm && spk dev --pkg-def=/opt/app/.sandstorm/sandstorm-pkgdef.capnp:pkgdef']' returned non-zero exit status 1
vagrant-spk returned -1
```

The problem is, the file really exist. I even checked from ssh.

**Comment by paulproteus** [comment]
In /opt/app/.sandstorm/sandstorm-pkgdef.capnp,

instead of: /opt/app/images/preview/catalog.jpg

can you try writing

../images/preview/catalog.jpg

And tell me if the problem goes away?

**Comment by vionemc** [comment]
Yup, it goes away :) Although I can't check whether it's really loaded or not since it's not submitted to the market. 

We can close this issue I think. At least for now.

**Comment by paulproteus** [comment]
+1​
